# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66abfa7afdc8048aa65b38a98561b7056bff20b3b369bdb60ea36e5ef222ec8c7c561de8bc6883e408223306f45e2a0dbd080036eb68dd4616e1454d31dcdc07

test:
  secret_key_base: 21733de6ef20d73c0d4b14e36f955f330fbc9e7d61f8c094fe4182135e78dfed76e378c3323698251633677b893a3eb08005f6b194dc1d0db5ae42dd0d64d1f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
